<div>
  <div class="inputs">
    <p>
      <?php echo $this->translate('Add custom CSS for sites.'); ?><br/>
      <?php echo $this->translate("Note: CSS rules defined for 'Default' will only be used if no CSS is defined for a specific site in this module."); ?><br/>
      <?php echo $this->translate('Warning: the following tags cannot be used in selectors:'); ?>
      <b>body, head, html</b>.<br/>
      <?php echo sprintf($this->translate('For instance, if you define a rule like %s, it will be removed when submitting your changes.'), '<code>body {color: red;}</code>'); ?>
    </p>
    <div id="csseditor_site">
      <?php
        echo $this->siteSelect('site', [
            'empty_option' => $this->translate('Default'),
        ]);
      ?>
    </div>
    <div>
      <?php echo $this->formTextarea($textarea); ?>
    </div>

  </div>
<br/><br/>
<a class="button" id="save">Save</a>
<a class="button" id="restore">Restore</a>

</span>

</div>

